version: "3.7"
services:
  db:
    image: postgres:12
    container_name: LaborEE-DB
    environment:
      POSTGRES_USER: labor
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laborV2
    ports:
        - "5432:5432"
    volumes:
        - ./db:/var/lib/postgresql/data